import { test, describe, before, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const Module = require('node:module');

// Intercept next/headers for raw Node runner compatibility
const originalRequire = Module.prototype.require;
Module.prototype.require = function (id) {
  if (id === 'next/headers' || id === 'next/headers.js') {
    return {
      cookies: async () => ({
        get: () => ({ value: 'test-session-token' })
      })
    };
  }
  return originalRequire.apply(this, arguments);
};

describe('Migración Búsquedas: Desacoplamiento id_busqueda vs codigo_busqueda', () => {
  let crearBusquedaAPI;
  let getBusquedasAPI;
  let originalFetch;
  let originalEnvMocks;
  let originalAtsUrl;

  before(async () => {
    originalFetch = globalThis.fetch;
    originalEnvMocks = process.env.NEXT_PUBLIC_USE_MOCKS;
    originalAtsUrl = process.env.NEXT_PUBLIC_ATS_API_URL;

    const module = await import('../src/actions/busquedas.ts');
    crearBusquedaAPI = module.crearBusquedaAPI;
    getBusquedasAPI = module.getBusquedasAPI;
  });

  afterEach(() => {
    globalThis.fetch = originalFetch;
    if (originalEnvMocks !== undefined) {
      process.env.NEXT_PUBLIC_USE_MOCKS = originalEnvMocks;
    } else {
      delete process.env.NEXT_PUBLIC_USE_MOCKS;
    }
    if (originalAtsUrl !== undefined) {
      process.env.NEXT_PUBLIC_ATS_API_URL = originalAtsUrl;
    } else {
      delete process.env.NEXT_PUBLIC_ATS_API_URL;
    }
  });

  test('1. crearBusquedaAPI en modo Mock genera id_busqueda (Firestore UUID) y preserva codigo_busqueda', async () => {
    process.env.NEXT_PUBLIC_USE_MOCKS = "true";

    const payload = {
      cliente: "Cliente Test",
      perfil_busqueda: "Desarrollador Fullstack",
      estado_fase: "Abierta",
      responsable_operativo: "Carlos M.",
      responsable_validacion: "Ana L.",
      fecha_inicio_objetivo: "2026-09-01",
      codigo_busqueda: "REQ-TEST-100"
    };

    const res = await crearBusquedaAPI(payload);

    assert.equal(res.status, 201);
    assert.equal(res.success, true);
    assert.equal(res.data.codigo_busqueda, "REQ-TEST-100");
    assert.ok(res.data.id_busqueda, "Debe poseer un id_busqueda asignado");
  });

  test('2. crearBusquedaAPI envía codigo_busqueda e id_busqueda en el payload REST hacia Cloud Run', async () => {
    delete process.env.NEXT_PUBLIC_USE_MOCKS;
    const testCloudRunUrl = "https://backend-test.a.run.app";
    process.env.NEXT_PUBLIC_ATS_API_URL = testCloudRunUrl;

    let capturedUrl = "";
    let capturedOptions = null;

    globalThis.fetch = async (url, options) => {
      capturedUrl = url;
      capturedOptions = options;
      return {
        status: 201,
        json: async () => ({
          status: "success",
          data: { id_busqueda: "firestore-autogenerated-uuid-xyz", codigo_busqueda: "REQ-2026-X" }
        })
      };
    };

    const payload = {
      cliente: "Banco Test",
      perfil_busqueda: "DevOps Engineer",
      estado_fase: "evaluacion_tecnica",
      responsable_operativo: "Sofia R.",
      responsable_validacion: "Javier O.",
      fecha_inicio_objetivo: "2026-10-01",
      codigo_busqueda: "REQ-2026-X"
    };

    const res = await crearBusquedaAPI(payload);

    assert.equal(capturedUrl, `${testCloudRunUrl}/api/v1/busquedas`);
    const parsedBody = JSON.parse(capturedOptions.body);
    assert.equal(parsedBody.codigo_busqueda, "REQ-2026-X");
    assert.equal(res.status, 201);
  });

  test('3. getBusquedasAPI mapea id_busqueda y codigo_busqueda correctamente con fallback visual para legacy', async () => {
    delete process.env.NEXT_PUBLIC_USE_MOCKS;
    process.env.NEXT_PUBLIC_ATS_API_URL = "https://backend-test.a.run.app";

    globalThis.fetch = async () => {
      return {
        ok: true,
        json: async () => ({
          data: [
            {
              id_busqueda: "firestore-uuid-001",
              codigo_busqueda: "REQ-HUMAN-01",
              identificacion: { cliente: "Empresa A", hiring_manager: "Edith" },
              perfil_tecnico: { rol_solicitado: "Senior React" },
              estado_sla: { estado_busqueda: "Abierta" }
            },
            {
              // Objeto legacy sin codigo_busqueda
              id: "REQ-LEGACY-002",
              identificacion: { cliente: "Empresa B", hiring_manager: "Marcos" },
              perfil_tecnico: { rol_solicitado: "Backend Go" },
              estado_sla: { estado_busqueda: "Abierta" }
            }
          ]
        })
      };
    };

    const list = await getBusquedasAPI();

    assert.equal(list.length, 2);
    // Nuevo registro con desacoplamiento
    assert.equal(list[0].id_busqueda, "firestore-uuid-001");
    assert.equal(list[0].codigo_busqueda, "REQ-HUMAN-01");
    
    // Registro legacy con fallback
    assert.equal(list[1].id_busqueda, "REQ-LEGACY-002");
    assert.equal(list[1].codigo_busqueda, "REQ-LEGACY-002");
  });
});
